---
name: light
price: 60
stone_ac: 2
stone_maxdex: 1
stone_dr_piercing: 0
stone_dr_slashing: 0
stone_dr_bashing: 0
stone_skillpenalty: -3
bronze_ac: 3
bronze_maxdex: 2
bronze_dr_piercing: 1
bronze_dr_slashing: 0
bronze_dr_bashing: 0
bronze_skillpenalty: -1
iron_AC: 3
iron_maxdex: 3
iron_dr_piercing: 1
iron_dr_slashing: 0
iron_dr_bashing: 0
iron_skillpenalty: -2
steel_AC: 4
steel_maxdex: 2
bronze_dr_piercing: 
bronze_dr_slashing: 
bronze_dr_bashing: 
steel_dr_piercing: 1
steel_dr_slashing: 1
steel_dr_bashing: 0
steel_skillpenalty: -1
---
name: heavy
price: 240
stone_AC: 4
stone_maxdex: 0
stone_dr_piercing: 0
stone_dr_slashing: 0
stone_dr_bashing: 1
stone_skillpenalty: 0
bronze_AC: 5
bronze_maxdex: 1
bronze_dr_piercing: 0
bronze_dr_slashing: 1
bronze_dr_bashing: 0
bronze_skillpenalty: -4
iron_AC: 6
iron_maxdex: 1
iron_dr_piercing: 0
iron_dr_slashing: 1
iron_dr_bashing: 1
iron_skillpenalty: -3
steel_AC: 7
steel_maxdex: 2
steel_dr_piercing: 1
steel_dr_slashing: 1
steel_dr_bashing: 1
steel_skillpenalty: -3
---
name: helmet
price: 12
stone_AC: 0
stone_maxdex: 0
stone_dr_piercing: 0
stone_dr_slashing: 0
stone_dr_bashing: 0
stone_skillpenalty: 0
bronze_AC: 1
bronze_maxdex: -1
bronze_dr_piercing: 0
bronze_dr_slashing: 0
bronze_dr_bashing: 0
bronze_skillpenalty: -2
iron_AC: 1
iron_maxdex: 0
iron_dr_piercing: 0
iron_dr_slashing: 0
iron_dr_bashing: 0
iron_skillpenalty: -1
steel_AC: 1
steel_maxdex: 0
steel_dr_piercing: 0
steel_dr_slashing: 0
steel_dr_bashing: 0
steel_skillpenalty: -1
---
name: shield
price: 20
stone_AC: 1
stone_maxdex: -2
stone_dr_piercing: 0
stone_dr_slashing: 0
stone_dr_bashing: 0
stone_skillpenalty: -2
bronze_AC: 2
bronze_maxdex: -1
bronze_dr_piercing: 0
bronze_dr_slashing: 0
bronze_dr_bashing: 0
bronze_skillpenalty: -2
iron_AC: 2
iron_maxdex: -1
iron_dr_piercing: 0
iron_dr_slashing: 0
iron_dr_bashing: 0
iron_skillpenalty: -1
steel_AC: 1
steel_maxdex: 0
steel_dr_piercing: 0
steel_dr_slashing: 0
steel_dr_bashing: 0
steel_skillpenalty: 0
---
