---
name: light
price: 60
stone_AC: 2
stone_maxdex: 1
stone_damagereduction: !!null
stone_skillpenalty: -3
bronze_AC: 3
bronze_maxdex: 2
bronze_damagereduction: piercing
bronze_skillpenalty: -1
iron_AC: 3
iron_maxdex: 3
iron_damagereduction: piercing
iron_skillpenalty: -2
steel_AC: 4
steel_maxdex: 2
steel_damagereduction: piercing slashing
steel_skillpenalty: -1
---
name: heavy
price: 240
stone_AC: 4
stone_maxdex: 0
stone_damagereduction: bashing
stone_skillpenalty: 0
bronze_AC: 5
bronze_maxdex: 1
bronze_damagereduction: slashing
bronze_skillpenalty: -4
iron_AC: 6
iron_maxdex: 1
iron_damagereduction: slashing bashing
iron_skillpenalty: -3
steel_AC: 7
steel_maxdex: 2
steel_damagereduction: piercing slashing bashing
steel_skillpenalty: -3
---
name: helmet
price: 12
stone_AC: 0
stone_maxdex: 0
stone_damagereduction: !!null
stone_skillpenalty: 0
bronze_AC: 1
bronze_maxdex: -1
bronze_damagereduction: !!null
bronze_skillpenalty: -2
iron_AC: 1
iron_maxdex: 0
iron_damagereduction: !!null
iron_skillpenalty: -1
steel_AC: 1
steel_maxdex: 0
steel_damagereduction: !!null
steel_skillpenalty: -1
---
name: shield
price: 20
stone_AC: 1
stone_maxdex: -2
stone_damagereduction: !!null
stone_skillpenalty: -2
bronze_AC: 2
bronze_maxdex: -1
bronze_damagereduction: !!null
bronze_skillpenalty: -2
iron_AC: 2
iron_maxdex: -1
iron_damagereduction: !!null
iron_skillpenalty: -1
steel_AC: 1
steel_maxdex: 0
steel_damagereduction: !!null
steel_skillpenalty: 0
---
