---
name: Alcance
group: magic
skill_check: []
specification: !!null
prerequisite: !!null
penalties_from_armour: !!null
description: |
    <p>This skill allows the character to change the
    range of his wizard spells and warlock powers
    from short to medium, or from medium to
    long. It cannot upgrade range from short to
    long.</p>
    <p>Wizards use up one circle of their reserve to
    do this. Therefore, they cannot do this to a
    spell of their highest circle.</p>
    <p>When warlocks use alcance, they face a -4
    penalty to the power-check.</p>
---
name: Alertness
group: all
Specification: !!null
prerequisite: !!null
penalties_from_armour: !!null
description: |
    <p>This skill teaches the character to be alert 
    for the unexpected. It helps him to notice thieves, 
    or to react swiftly when standing guard.</p>
    <p>Altertness is the opposing skill for stealth,
    sleight of hand and quickdraw. It also often 
    determines surprise.</p>
---

